#!/usr/bin/env python

import sys
import yaml_server.YamlServerMain

if __name__ == "__main__":
    ret = 2
    daemon = yaml_server.YamlServerMain.YamlServerMain()
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            ret = daemon.start()
        elif 'stop' == sys.argv[1]:
            ret = daemon.stop()
        elif 'restart' == sys.argv[1]:
            ret = daemon.restart()
        elif 'status' == sys.argv[1]:
            ret = daemon.status()
        else:
            print "Unknown command %s" % sys.argv[1]
            ret = 2
    else:
        print "usage: %s start|stop|restart|status" % sys.argv[0]
        ret = 2
    
    sys.exit(ret)