#!/usr/bin/env python

# chkconfig: 2345 80 20
# description: Export YAML configuration dirs via HTTP

### BEGIN INIT INFO
# Provides:          yaml_server
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Export YAML configuration dirs via HTTP
# Description:       Export YAML configuration dirs via HTTP
#                    to access configuration items that are
#                    provided in many files as a single YAML
#                    document.
### END INIT INFO

import sys
import yaml_server.YamlServerMain

if __name__ == "__main__":
    sys.exit(yaml_server.YamlServerMain.YamlServerMain().service_script())